[package]
name = "emscripten-sys-example"
version = "0.1.0"
edition = "2018"

[dependencies]
serde_json = "1.0"

[target.'cfg(target_os = "emscripten")'.dependencies]
emscripten-sys = { git = "https://github.com/sinato/emscripten-sys", branch = "fix-for-current-rust" }
